### ISSUE TITLE
Support for OpenCV 4.6 ?

### ISSUE THREAD

**Issue by unfa** [Crowsinc/LiveVisionKit#11]
I'm trying to use LiveVisionKit on Arch Linux - the problem is - Arch Linux packages OpenCV 4.6, and I am having though luck compiling 4.5.5 from source.

Is it possible to somehow make LVK work with OpenCV 4.6?

**Comment by Crowsinc** [comment]
I'm happy to release an update upgrading LVK to use OpenCV 4.6 some time this week.

Note that support for running the stabilizer, de-blocker, lens correction, and calibration filters as effects filters is currently disabled for Linux due to stability/driver issues. But they should run just fine as video filters if you have that option available to you!

**Comment by Crowsinc** [comment]
I've updated LVK to OpenCV 4.6; but it will be released alongside some other improvements to Linux in LVK 1.2.1

**Comment by unfa** [comment]
Thanks! I'm looking forward to being able to use the LVK filters on Linux :)

**Comment by Crowsinc** [comment]
Sorry for the delay, I've been rather busy outside of the project! But this has now been released as part of update 1.2.1, Please let me know if you encounter any issues.

**Comment by unfa** [comment]
Thanks! I'll try in the latest stable version of OBS.
