### ISSUE TITLE
Plugin doesnt load, loadlibrary failed

### ISSUE THREAD

**Issue by helianto** [Crowsinc/LiveVisionKit#12]
**System/Software Setup**
 - **LiveVisionKit Version:** last published
 - **OBS Studio Version:** 27.2.4
 - **OS:** *Windows 10
 - **GPU:** nvidia 1650
 - **CPU:** *xeon
 - 
**OBS Log:**:09:53:12.730: Source ID 'image_source' not found
09:53:12.730: Failed to create source 'durchblick_placeholder'!
09:53:12.770: [AMF] Unable to load 'amfrt64.dll', error code 126.
09:53:12.772: [AMF] AMF Test failed due to one or more errors.
09:53:12.772: Failed to initialize module 'enc-amf.dll'
09:53:12.786: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
09:53:12.787: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
09:53:12.787: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
09:53:14.118: LoadLibrary failed for '../../obs-plugins/64bit/LiveVisionKit.dll': (null) (1114)
09:53:14.118: Module '../../obs-plugins/64bit/LiveVisionKit.dll' not loaded

**Issue Description**
After installation of plugin, it doesnt load

**Comment by Crowsinc** [comment]
Hi, could you please provide me with your full OBS log?

**Comment by helianto** [comment]
[2022-09-28 11-27-46.txt](https://github.com/Crowsinc/LiveVisionKit/files/9663498/2022-09-28.11-27-46.txt)

**Comment by Crowsinc** [comment]
Since this is an error on the Windows OS side of things rather than the LiveVisionKit code, there's no way to determine what is causing this without some trial and error. However, I suspect it may be because LiveVisionKit 1.2 makes use of the AVX extensions, which are not supported by your Xeon X5675.

There's no guarantee that this is what is actually causing the library to fail loading, because the given error code (1114) does not provide any information; however I will reconsider whether AVX is really necessary for the upcoming LiveVisionKit 1.2.1 update.

**Comment by helianto** [comment]
Probably this is... i will test in other xeon without avx to confirm it

**Comment by ryanfurtner** [comment]
Im getting the same issue and I think my specs are pretty close to the recommended specs

[2023-02-19 09-32-26.txt](https://github.com/Crowsinc/LiveVisionKit/files/10778208/2023-02-19.09-32-26.txt)

**Comment by Crowsinc** [comment]
Hi, you may have accidentally installed the OBS 28+ version of LVK 1.2.1. OBS 28 plugins are not backwards compatible. You will need the OBS 27 version, named " OBS27-LiveVisionKit-1.2.1-Windows.zip" in the releases page. 

Please let me know if that fixes your issue.
