### ISSUE TITLE
Build from source (against older version of libopencv)

### ISSUE THREAD

**Issue by cornop** [Crowsinc/LiveVisionKit#15]
**What is the requested feature?**
*Describe what it is and what it's supposed to accomplish.*

I would like to build this library from source, i.e. using a provided makefile or similar.

**Why do you want this feature?**
*Describe why it's needed, what problems it solves.*
*If it is related to an issue, reference it here.*

I'm on a distribution (Debian stable) that doesn't provide libopencv 4.6 yet. Building from source would enable me to build against my distribution's version of libopencv.

For reference, loading the plugin fails with:

```
04:02:17.010: os_dlopen(.../com.obsproject.Studio/config/obs-studio/plugins/LiveVisionKit/bin/64bit/libLiveVisionKit.so->.../com.obsproject.Studio/config/obs-studio/plugins/LiveVisionKit/bin/64bit/libLiveVisionKit.so): libopencv_core.so.406: cannot open shared object file: No such file or directory
04:02:17.010:
04:02:17.013: os_dlopen(.../com.obsproject.Studio/config/obs-studio/plugins/LiveVisionKit/bin/64bit/libLiveVisionKit.so->.../com.obsproject.Studio/config/obs-studio/plugins/LiveVisionKit/bin/64bit/libLiveVisionKit.so): libopencv_core.so.406: cannot open shared object file: No such file or directory
04:02:17.013:
04:02:17.013: Module '.../com.obsproject.Studio/config/obs-studio/plugins/LiveVisionKit/bin/64bit/libLiveVisionKit.so' not loaded
```

And `apt install libopencv-core\*` provides `/usr/lib/x86_64-linux-gnu/libopencv_core.so.4.5` and `/usr/lib/x86_64-linux-gnu/libopencv_core.so.4.5.1`.

**Comment by Crowsinc** [comment]
Hi, this is currently in the works!

**Comment by Crowsinc** [comment]
The source files now come with accompanying cmake for compilation. You can find some basic instructions can be found [here](https://github.com/Crowsinc/LiveVisionKit/wiki/Build-Guide). 

There were major architectural changes as part of adding cmake, so be aware that the project may not be as stable as the latest release. I would recommend compiling the `modular` branch instead of `main`. 

Let me know if you run into any issues!
