### ISSUE TITLE
FidelityFX Super Resolution

### ISSUE THREAD

**Issue by ASchneiderBR** [Crowsinc/LiveVisionKit#4]
**System/Software Setup**
 - **LiveVisionKit Version:** v1.0.1
 - **OBS Studio Version:** v27.2.3
 - **OS:** Windows 10
 - **GPU:** RTX 2080ti
 - **CPU:** Ryzen 9 3900x

**Issue Description**
Hello. It seems that FidelityFX Super Resolution is not respecting the original source aspect ratio. I was trying it with a 1:1 aspect ratio media source and it always scales to a 16x9 aspect ratio.

**Expected Behavior**
It would be nice to be able to select the exact resolution or just something like 2x, 3x and so on.

Thank you.

**Comment by Crowsinc** [comment]
Hi. Yes, the FSR filter is missing a lot of useful settings because it wasn't originally meant to be a general purpose scaling filter. Finer control like custom resolutions and cropping is planned to be included in the next feature update coming soon. The functionality already exists, it just needs to be connected to the filter's UI.

**Comment by ASchneiderBR** [comment]
Hello. Thanks for the information. Have a great day!

**Comment by Crowsinc** [comment]
Issue is now fixed as of [LiveVisionKit 1.1.0](https://github.com/Crowsinc/LiveVisionKit/releases/tag/v1.1.0)
