### ISSUE TITLE
video stabilization filter instantly crashing obs

### ISSUE THREAD

**Issue by Doomeron** [Crowsinc/LiveVisionKit#7]
**System/Software Setup**
 - **LiveVisionKit Version:** *1.1.1.*
 - **OBS Studio Version:** *27.2.4 (64-bit).*
 - **OS:** *Windows 10, 10.0 build 19044 (release: 2009; revision: 1288; 64-bit).*
 - **GPU:** *Nvidia RTX 3070.*
 - **CPU:** *Intel(R) Core(TM) i7-2700K CPU @ 4.0GHz.*

**Issue Description**
Attempting to apply video stabilization filter to various sources (Media source .mp4 file, Webcam & SRT feeds) crashes my obs. 

I used a portable obs setup at first, then an installed version. also tried various output encoders to rule them out also (x264,nvenc,nvenc new via ffmpeg)

**Reproduction Steps**
Enabling video stabilization filter instantly crashes my obs.

**Comment by Doomeron** [comment]
i also tried various Nvidia graphics card drivers 512.15, 497.29, 451.48

**Comment by Crowsinc** [comment]
Hi, I believe this crash is due to LiveVisionKit being compiled using AVX2 optimizations which aren't supported by your i7 2700k. Support started with 4th gen Intel processors. If this is true, then I would imagine that some of the other filters would also crash?

Regardless, I have recompiled LiveVisionKit 1.1.1 without AVX2 and updated the release files. Please let me know if you still run into any issues.

**Comment by Doomeron** [comment]
Before i updated to your newer version i tested the rest of the filters for you to see if they crash at all

Adaptive Deblocker, Lens Correction, Calibration Tool all run without any issues

AMD FSR 1.0 Video Scaler crashed my OBS when i change any of the crop settings and then playing the video source

as does AMD Fidelity FX Sharpening upon enabling the filter

i will try the updated version and report back

**Comment by Doomeron** [comment]
all fixed!!! 👯 now to do more testing thank you sir
